"""
Trading Strategies Module
=========================
Implements multiple trading strategies for Polymarket:
- Value: Buy underpriced outcomes based on analysis
- Momentum: Trade in the direction of price movements  
- Mean Reversion: Trade against extreme price movements
- Market Making: Provide liquidity by posting two-sided quotes
"""

import time
import json
from dataclasses import dataclass, field
from typing import Optional
from loguru import logger

from config import Config
from client import PolymarketClient


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    token_id: str
    market_id: str
    question: str
    side: str  # "BUY" or "SELL"
    price: float
    size: float
    confidence: float  # 0.0 to 1.0
    reason: str
    neg_risk: bool = False
    tick_size: str = "0.01"

    def __repr__(self):
        return (
            f"Signal({self.side} {self.size:.1f}@{self.price:.3f} "
            f"conf={self.confidence:.2f} '{self.question[:50]}')"
        )


class MarketAnalyzer:
    """Analyzes markets to identify trading opportunities."""

    def __init__(self, client: PolymarketClient, config: Config):
        self.client = client
        self.config = config

    def score_market(self, market: dict) -> float:
        """Score a market based on desirability (0-1). Higher = better opportunity."""
        score = 0.0

        # Volume factor (prefer active markets)
        volume_24h = float(market.get("volume24hr", 0) or 0)
        if volume_24h > 10000:
            score += 0.3
        elif volume_24h > 1000:
            score += 0.2
        elif volume_24h > 100:
            score += 0.1

        # Liquidity factor
        liquidity = float(market.get("liquidity", 0) or 0)
        if liquidity >= self.config.strategy.min_liquidity:
            score += 0.3
        elif liquidity > 500:
            score += 0.1

        # Price factor (prefer markets near 0.5 for more volatility potential)
        outcomes = market.get("outcomePrices", "[]")
        if isinstance(outcomes, str):
            try:
                outcomes = json.loads(outcomes)
            except (json.JSONDecodeError, TypeError):
                outcomes = []

        if outcomes:
            try:
                yes_price = float(outcomes[0])
                # Markets near 50% have more upside potential both ways
                distance_from_50 = abs(yes_price - 0.5)
                if distance_from_50 < 0.15:
                    score += 0.2
                elif distance_from_50 < 0.30:
                    score += 0.1
            except (ValueError, IndexError):
                pass

        # Order book availability
        if market.get("enableOrderBook"):
            score += 0.2

        return min(score, 1.0)

    def analyze_orderbook(self, token_id: str) -> dict:
        """Analyze orderbook depth and spread."""
        book = self.client.get_orderbook(token_id)
        if not book:
            return {"liquid": False}

        bids = book.get("bids", [])
        asks = book.get("asks", [])

        if not bids or not asks:
            return {"liquid": False}

        best_bid = float(bids[0]["price"])
        best_ask = float(asks[0]["price"])
        spread = best_ask - best_bid
        midpoint = (best_bid + best_ask) / 2

        bid_depth = sum(float(b["size"]) for b in bids[:5])
        ask_depth = sum(float(a["size"]) for a in asks[:5])

        return {
            "liquid": True,
            "best_bid": best_bid,
            "best_ask": best_ask,
            "spread": spread,
            "midpoint": midpoint,
            "bid_depth": bid_depth,
            "ask_depth": ask_depth,
            "spread_pct": spread / midpoint if midpoint > 0 else 1.0,
            "imbalance": (bid_depth - ask_depth) / (bid_depth + ask_depth) if (bid_depth + ask_depth) > 0 else 0,
        }

    def get_price_momentum(self, token_id: str) -> Optional[float]:
        """Calculate recent price momentum (-1 to 1)."""
        history = self.client.get_prices_history(token_id, interval="6h")
        if not history or len(history) < 5:
            return None

        prices = [float(p["p"]) for p in history[-10:]]
        if len(prices) < 3:
            return None

        recent_avg = sum(prices[-3:]) / 3
        older_avg = sum(prices[:3]) / 3

        if older_avg == 0:
            return None

        momentum = (recent_avg - older_avg) / older_avg
        return max(-1.0, min(1.0, momentum * 5))  # Scale and clamp


class ValueStrategy:
    """
    Value Strategy: Look for markets where the price seems mispriced
    relative to orderbook signals and volume patterns.
    """

    def __init__(self, analyzer: MarketAnalyzer, config: Config):
        self.analyzer = analyzer
        self.config = config

    def generate_signals(self, markets: list[dict]) -> list[Signal]:
        """Generate buy signals for undervalued outcomes."""
        signals = []

        for market in markets:
            try:
                signal = self._analyze_market(market)
                if signal:
                    signals.append(signal)
            except Exception as e:
                logger.debug(f"Error analyzing market: {e}")
                continue

        # Sort by confidence
        signals.sort(key=lambda s: s.confidence, reverse=True)
        return signals[:self.config.strategy.max_active_markets]

    def _analyze_market(self, market: dict) -> Optional[Signal]:
        """Analyze a single market for value opportunities."""
        clob_token_ids = market.get("clobTokenIds", "[]")
        if isinstance(clob_token_ids, str):
            try:
                clob_token_ids = json.loads(clob_token_ids)
            except (json.JSONDecodeError, TypeError):
                return None

        if not clob_token_ids or len(clob_token_ids) < 2:
            return None

        # Analyze YES token
        yes_token = clob_token_ids[0]
        no_token = clob_token_ids[1]

        book_analysis = self.analyzer.analyze_orderbook(yes_token)
        if not book_analysis.get("liquid"):
            return None

        midpoint = book_analysis["midpoint"]
        spread = book_analysis["spread"]
        imbalance = book_analysis["imbalance"]
        spread_pct = book_analysis["spread_pct"]

        # Skip if spread is too wide (illiquid)
        if spread_pct > 0.10:
            return None

        # Value signal: orderbook imbalance suggests mispricing
        confidence = 0.0
        side = None
        target_price = None
        reason = ""

        # Buying opportunity: more bid depth (buyers) but price still low
        if imbalance > 0.3 and midpoint < 0.65:
            confidence = min(0.8, abs(imbalance) * 0.8)
            side = "BUY"
            target_price = book_analysis["best_ask"]  # Buy at ask
            reason = f"Strong bid imbalance ({imbalance:.2f}), midpoint {midpoint:.3f}"

        # Selling opportunity: more ask depth (sellers) but price still high
        elif imbalance < -0.3 and midpoint > 0.35:
            confidence = min(0.8, abs(imbalance) * 0.8)
            side = "SELL"
            target_price = book_analysis["best_bid"]  # Sell at bid
            reason = f"Strong ask imbalance ({imbalance:.2f}), midpoint {midpoint:.3f}"

        # Momentum factor
        momentum = self.analyzer.get_price_momentum(yes_token)
        if momentum is not None:
            if side == "BUY" and momentum > 0.1:
                confidence += 0.1
                reason += f", positive momentum ({momentum:.2f})"
            elif side == "SELL" and momentum < -0.1:
                confidence += 0.1
                reason += f", negative momentum ({momentum:.2f})"

        if not side or confidence < 0.3:
            return None

        # Check minimum edge
        if side == "BUY" and (1.0 - target_price) < self.config.strategy.min_edge:
            return None
        if side == "SELL" and target_price < self.config.strategy.min_edge:
            return None

        token_id = yes_token if side == "BUY" else yes_token
        tick_size = self.analyzer.client.get_tick_size(token_id)
        neg_risk = self.analyzer.client.get_neg_risk(token_id)

        return Signal(
            token_id=token_id,
            market_id=market.get("conditionId", market.get("id", "")),
            question=market.get("question", "Unknown"),
            side=side,
            price=target_price,
            size=self.config.strategy.order_size,
            confidence=confidence,
            reason=reason,
            neg_risk=neg_risk,
            tick_size=tick_size,
        )


class MomentumStrategy:
    """
    Momentum Strategy: Trade in the direction of recent price movements.
    """

    def __init__(self, analyzer: MarketAnalyzer, config: Config):
        self.analyzer = analyzer
        self.config = config

    def generate_signals(self, markets: list[dict]) -> list[Signal]:
        """Generate signals based on price momentum."""
        signals = []

        for market in markets:
            try:
                signal = self._analyze_market(market)
                if signal:
                    signals.append(signal)
            except Exception as e:
                logger.debug(f"Error in momentum analysis: {e}")
                continue

        signals.sort(key=lambda s: s.confidence, reverse=True)
        return signals[:self.config.strategy.max_active_markets]

    def _analyze_market(self, market: dict) -> Optional[Signal]:
        """Analyze a market for momentum signals."""
        clob_token_ids = market.get("clobTokenIds", "[]")
        if isinstance(clob_token_ids, str):
            try:
                clob_token_ids = json.loads(clob_token_ids)
            except (json.JSONDecodeError, TypeError):
                return None

        if not clob_token_ids:
            return None

        yes_token = clob_token_ids[0]
        momentum = self.analyzer.get_price_momentum(yes_token)

        if momentum is None:
            return None

        # Only trade on strong momentum
        if abs(momentum) < 0.3:
            return None

        book_analysis = self.analyzer.analyze_orderbook(yes_token)
        if not book_analysis.get("liquid"):
            return None

        midpoint = book_analysis["midpoint"]

        # Don't chase into extremes
        if midpoint > 0.90 or midpoint < 0.10:
            return None

        if momentum > 0.3:
            side = "BUY"
            price = book_analysis["best_ask"]
            reason = f"Strong upward momentum ({momentum:.2f})"
        else:
            side = "SELL"
            price = book_analysis["best_bid"]
            reason = f"Strong downward momentum ({momentum:.2f})"

        confidence = min(0.85, abs(momentum) * 0.9)

        tick_size = self.analyzer.client.get_tick_size(yes_token)
        neg_risk = self.analyzer.client.get_neg_risk(yes_token)

        return Signal(
            token_id=yes_token,
            market_id=market.get("conditionId", market.get("id", "")),
            question=market.get("question", "Unknown"),
            side=side,
            price=price,
            size=self.config.strategy.order_size,
            confidence=confidence,
            reason=reason,
            neg_risk=neg_risk,
            tick_size=tick_size,
        )


class MeanReversionStrategy:
    """
    Mean Reversion Strategy: Bet against extreme price movements,
    expecting a return toward the mean.
    """

    def __init__(self, analyzer: MarketAnalyzer, config: Config):
        self.analyzer = analyzer
        self.config = config

    def generate_signals(self, markets: list[dict]) -> list[Signal]:
        """Generate contrarian signals."""
        signals = []

        for market in markets:
            try:
                signal = self._analyze_market(market)
                if signal:
                    signals.append(signal)
            except Exception as e:
                logger.debug(f"Error in mean reversion analysis: {e}")
                continue

        signals.sort(key=lambda s: s.confidence, reverse=True)
        return signals[:self.config.strategy.max_active_markets]

    def _analyze_market(self, market: dict) -> Optional[Signal]:
        """Analyze a market for mean reversion opportunities."""
        clob_token_ids = market.get("clobTokenIds", "[]")
        if isinstance(clob_token_ids, str):
            try:
                clob_token_ids = json.loads(clob_token_ids)
            except (json.JSONDecodeError, TypeError):
                return None

        if not clob_token_ids:
            return None

        yes_token = clob_token_ids[0]

        # Get price history to find average
        history = self.analyzer.client.get_prices_history(yes_token, interval="1w")
        if not history or len(history) < 10:
            return None

        prices = [float(p["p"]) for p in history]
        avg_price = sum(prices) / len(prices)
        current_price = prices[-1]

        # Calculate deviation from mean
        deviation = (current_price - avg_price) / avg_price if avg_price > 0 else 0

        # Only trade on significant deviations
        if abs(deviation) < 0.15:
            return None

        book_analysis = self.analyzer.analyze_orderbook(yes_token)
        if not book_analysis.get("liquid"):
            return None

        # Price went up too much -> sell (expect reversion)
        if deviation > 0.15 and current_price > 0.25:
            side = "SELL"
            price = book_analysis["best_bid"]
            reason = f"Mean reversion: price {current_price:.3f} > avg {avg_price:.3f} (+{deviation*100:.1f}%)"
        # Price went down too much -> buy (expect reversion)
        elif deviation < -0.15 and current_price < 0.75:
            side = "BUY"
            price = book_analysis["best_ask"]
            reason = f"Mean reversion: price {current_price:.3f} < avg {avg_price:.3f} ({deviation*100:.1f}%)"
        else:
            return None

        confidence = min(0.75, abs(deviation) * 2)

        tick_size = self.analyzer.client.get_tick_size(yes_token)
        neg_risk = self.analyzer.client.get_neg_risk(yes_token)

        return Signal(
            token_id=yes_token,
            market_id=market.get("conditionId", market.get("id", "")),
            question=market.get("question", "Unknown"),
            side=side,
            price=price,
            size=self.config.strategy.order_size,
            confidence=confidence,
            reason=reason,
            neg_risk=neg_risk,
            tick_size=tick_size,
        )


def get_strategy(name: str, analyzer: MarketAnalyzer, config: Config):
    """Factory function to get strategy by name."""
    strategies = {
        "value": ValueStrategy,
        "momentum": MomentumStrategy,
        "mean_reversion": MeanReversionStrategy,
    }
    strategy_class = strategies.get(name.lower())
    if not strategy_class:
        logger.warning(f"Unknown strategy '{name}', defaulting to 'value'")
        strategy_class = ValueStrategy
    return strategy_class(analyzer, config)
